// Code generated by protoc-gen-go-errors-kitx. DO NOT EDIT.

package pbhelloworld

import (
	fmt "fmt"
	errorx "github.com/sado0823/go-kitx/errorx"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kitx package it is being compiled against.
var _ error = (*errorx.Error)(nil)

// 为某个枚举单独设置错误码
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errorx.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

// 为某个枚举单独设置错误码
func ErrorUserNotFound(format string, args ...interface{}) *errorx.Error {
	return errorx.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errorx.FromError(err)
	return e.Reason == ErrorReason_CONTENT_MISSING.String() && e.Code == 400
}

func ErrorContentMissing(format string, args ...interface{}) *errorx.Error {
	return errorx.New(400, ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}
